# Import
from yacs.config import CfgNode as CN

# Simple Baseline
SBL_NET = CN()

SBL_NET.RESNET_TYPE = 101
SBL_NET.IS_PRETRAIN = False
SBL_NET.NUM_LAYERS = 50
SBL_NET.DECONV_WITH_BIAS = False
SBL_NET.NUM_DECONV_LAYERS = 3
SBL_NET.NUM_DECONV_FILTERS = [256, 256, 256]
SBL_NET.NUM_DECONV_KERNELS = [4, 4, 4]
SBL_NET.FINAL_CONV_KERNEL = 1

# Hourglass
HG_NET = CN()

HG_NET.NUM_STACKS = 8  # 2 & 8
HG_NET.NUM_BLOCKS = 1

# CPN
CPN = CN()

CPN.IS_PRETRAIN = True
CPN.RESNET_TYPE = 50
CPN.CHANNEL_LIST = [2048, 1024, 512, 256]

# HRNET
HRNET = CN()

HRNET.PRETRAINED_PATH = 'resnet50-19c8e357.pth'

HRNET.PRETRAINED_LAYERS = ['conv1', 'bn1',
                           'conv2', 'bn2',
                           'layer1', 'transition1',
                           'stage2', 'transition2',
                           'stage3', 'transition3', 'stage4']
HRNET.STEM_INPLANES = 64
HRNET.FINAL_CONV_KERNEL = 1

HRNET.STAGE2 = CN()
HRNET.STAGE2.NUM_MODULES = 1
HRNET.STAGE2.NUM_BRANCHES = 2
HRNET.STAGE2.NUM_BLOCKS = [4, 4]
HRNET.STAGE2.NUM_CHANNELS = [32, 64]
HRNET.STAGE2.BLOCK = 'BASIC'
HRNET.STAGE2.FUSE_METHOD = 'SUM'

HRNET.STAGE3 = CN()
HRNET.STAGE3.NUM_MODULES = 1
HRNET.STAGE3.NUM_BRANCHES = 3
HRNET.STAGE3.NUM_BLOCKS = [4, 4, 4]
HRNET.STAGE3.NUM_CHANNELS = [32, 64, 128]
HRNET.STAGE3.BLOCK = 'BASIC'
HRNET.STAGE3.FUSE_METHOD = 'SUM'

HRNET.STAGE4 = CN()
HRNET.STAGE4.NUM_MODULES = 1
HRNET.STAGE4.NUM_BRANCHES = 4
HRNET.STAGE4.NUM_BLOCKS = [4, 4, 4, 4]
HRNET.STAGE4.NUM_CHANNELS = [32, 64, 128, 256]
HRNET.STAGE4.BLOCK = 'BASIC'
HRNET.STAGE4.FUSE_METHOD = 'SUM'


MODEL_EXTRAS = {
    'simple_baseline': SBL_NET,
    'hourglass': HG_NET,
    'hrnet': HRNET,
    'cpn': CPN
}